### ISSUE TITLE
How is IsLimit supposed to be used?

### ISSUE THREAD

**Issue by Alizter** [HoTT/Coq-HoTT#1125]
I am a bit baffled by the type Categories.Limits.IsLimit is giving.

```coq
Limits.IsLimit
     : forall (C D : PreCategory) (F : Core.Functor D C),
       (Core.pullback_along C (Functors.to_terminal D) / Core.cc_functor_from_terminal' (D -> C) F)%category -> Type
where
?H : [ |- Funext]

```

Shouldn't this just be an object of C?

**Comment by mikeshulman** [comment]
I assume that this is the property "being a limit" of a cone.

**Comment by Alizter** [comment]
It would be nice if the categories library had more (co)limits than it currently has. Currently we only have initial/terminal objects. (Co)products and (co)equalizers would be desirable.

**Comment by JasonGross** [comment]
> I assume that this is the property "being a limit" of a cone.

Indeed.  For general categories, you ask that the category has all (co)limits a certain shape of diagram using this definition.

> It would be nice if the categories library had more (co)limits than it currently has. Currently we only have initial/terminal objects. (Co)products and (co)equalizers would be desirable.

Feel free to add files which specialize Is(Co)Limit to these diagram shapes, and then prove that whatever categories you want have such objects.

Note that I was aiming to build up to the adjoint functor theorem, so didn't need to do much with (co)limits in concrete categories.

**Comment by Alizter** [comment]
@JasonGross Am I able to say the following things with the current categories library?

 * Has initial/terminal objects.
 * Has binary (co)products.
 * Has (co)equalizers

I don't think the third one is possible yet, but I am unsure if IsLimit (or IsColimit) can describe them. Once I define what the diagram of a given limit is, how do I use IsLimit to characterize the universal property?

Would I have to do this separately for all the cases I need?

Upon closer inspection I see that we have the following:

```coq
    Context `(has_colimits
              : forall F : Functor D C,
                  @IsColimit _ C D F (colimits F)).
```

It took me some time to realise that `colimits` was also a variable here. I see that it has the following type:

```coq
colimits
     : forall x : Functor D C,
       Core.comma_category
         (Core.cc_functor_from_terminal' (D -> C) x)
         (pullback_along C (Functors.to_terminal D))
```

So this is just the category of cones over F. How can extract the apex of this cone then?

**Comment by JasonGross** [comment]
You might want to resurrect the code I was trying to write to provide intro and elim rules, which I gave up on due to issues with non-convertibility of opposites (waiting on judgmental η for unit and for record types whose field types unify)
https://github.com/HoTT/HoTT/blob/ecd141815dc9c19a8ee736f5837d13275e45a976/theories/Categories/Limits/Core.v#L140-L169
You might also want to read the code in 
https://github.com/HoTT/HoTT/blob/master/theories/Categories/UniversalProperties.v

To answer your questions more directly:


> Am I able to say the following things with the current categories library?
> 
> * Has initial/terminal objects.

Use `nat_category 1` for the diagram category

> * Has binary (co)products.

Use `nat_category 2` for the diagram category

> * Has (co)equalizers

You'll need to construct the category with two objects and two non-identity morphisms going from one object to the other, for use as the diagram category.



> Once I define what the diagram of a given limit is, how do I use IsLimit to characterize the universal property?

You use the diagram category as `D`, and say that `C` has all `D`-shaped limits by using the construction that you found, saying that you have a way to produce a (co)limit from each functor from D to C, together with a proof that it is a (co)limit.



> So this is just the category of cones over F. How can extract the apex of this cone then?

It's not the category of cones, it's an object in the category of cones.  There's a coercion from category to Type that's hidden.

The quick-and-dirty way is to use the projections of the record type of objects in comma categories (`hnf` is your friend).  However, this breaks abstraction barriers and leads to slowness.  Since limits are thin wrappers around Kan extensions which are just universal morphisms specialized to particular categories and functors, you can get at the various pieces with the API defined in https://github.com/HoTT/HoTT/blob/master/theories/Categories/UniversalProperties.v
Ideally, you could use this to define the API for Kan extensions and then use that to define the API for (co)limits.

**Comment by Alizter** [comment]
>> So this is just the category of cones over F. How can extract the apex of this cone then?

>It's not the category of cones, it's an object in the category of cones. There's a coercion from category to Type that's hidden.

I meant the type of `colimits` here, not that I thought `colimits` gave a category. :-)
