### ISSUE TITLE
Turn FinSeq into an inductive type

### ISSUE THREAD

**Issue by Alizter** [HoTT/Coq-HoTT#1467]
I think it will be more convenient to have `FinSeq` as an inductive type, which we can then show to be equivalent to `Fin n -> A` later. There are at least two immediate advantages to doing this:

 1. We can pattern match on FinSeq directly, instead of having to induct on the cardinality.
 2. We avoid having to carry around funext so much.

@andreaslyn What do you think?

**Comment by andreaslyn** [comment]
I agree that the inductive `FinSeq` is often more convenient. Note that induction on `n` is not the only option for `Fin n -> A`. We can use induction on `Fin n -> A`, as with the inductive definition, by using `induction k using finseq_ind`. I do not think we need to remove the `Fin n -> A` version of `FinSeq`, since it is a useful alternative to the inductive. See the comment at https://github.com/HoTT/HoTT/pull/1428#discussion_r602624232, for an example where the inductive is not immediately useful.

**Comment by Alizter** [comment]
OK, then perhaps it is better to keep FinSeq as it is and instead define `Vector` as the inductive type version. That way we keep to the standard programming name.

I am not too worried about confusion with linear algebra however. We currently have no plans (that I am aware of) of developing linear algebra in the library, not to mention even if we do have a library about vectors, coq's namespacing should be able to handle this situation fine. It's also worth noting that linear algebra vectors and programming vectors share many operations and could possibly be developed as the same thing.

**Comment by Alizter** [comment]
Looking back at this, its not a particularly useful thing to do. Also, the `Vector` type from the Coq stdlib, is quite difficult to work with.
