### ISSUE TITLE
Decidable props

### ISSUE THREAD

**Issue by Alizter** [HoTT/Coq-HoTT#1468]
I'm currently trying to do some cleanup with the nat library but I am running into a bit of a problem: I don't know if I should be using DHProp. I see that previously discussions were had  in #654 and #683 about introducing decidable props for propositions. My opinion on the matter has seesawed somewhat so I would like to get a discussion going here on what to do.

Here is a common workflow when it comes to formalizing mathematics (I believe this is how ssreflect does it too):
 1. Define a proposition (say leq for nat as an inductive type).
 2. Define a boolean version of this proposition.
 3. Show that it is equivalent (in SSRs case that it "reflects").
 4. Get decidability from this

I've done this numerous times for various developments, but it always looks like I've done twice the amount of work I really need to.

Compare this with the DHProp version (which I think is happening):
 1. Define a DHProp for whatever it is you are doing
 2. It is automatically a hprop and decidable

Now this workflow looks nice, but I don't think it actually solves any problems. In fact, I don't see the difference between just working with booleans directly, since you can always coerce those into hprops.

I also don't like the fact that DHProp types actually compute. Sure this is neat where you can normalize `5 <= 7` and get a prop you know the answer to, but this is a nightmare when working in proofs. Sometimes you want to simplify a term, but coq simplifies the DHProps so things don't typecheck immediately (or at least take a long time too).

I feel as though it makes more sense to have a more rigid type, and this reflects how we work in practice. It seems to me that decidability is a property that we show after defining a property, not whilst defining it.

So I am interested in other peoples opinions, or perhaps even if I am missing something obvious.

**Comment by spitters** [comment]
Quick response. Yes, that's what ssr does.
There is also the decide equality tactic which is used in software
foundations/logical foundations.

**Comment by mikeshulman** [comment]
I don't understand what you mean by "DHProps compute".  A DHProp has an underlying *type*, not a boolean.  I guess if you define a DHProp by recursion the same way you would define a boolean-valued predicate, then it would compute, but you could just as well take the underlying type of a DHProp to be inductively defined.

**Comment by mikeshulman** [comment]
Would the problem you're seeing be solved with finer-grained simplification tactics that you could instruct to leave the DHProps alone?  How about declaring them Opaque or `simpl never`?

**Comment by Alizter** [comment]
The DHProp's that I have in mind is the current implementation of `leq` for nat for example. These do compute, and do so differently for simpl or cbn. Maybe this isn't such a big deal after all however. Its true that finer grained simplification tactics could solve the problem. Perhaps I am trying to be lazier than is permitted at the moment.

Another issue that DHProps have is that if I define a prop as on immediately, I can't declare it to be a typeclass. This is a pretty big limitation imo.

In the end, I want to understand the reason for considering decidable hprops in the first place, because I couldn't really understand the thread from before. Do we have any advantage in using DProps over how things are done in SSR for example?

**Comment by mikeshulman** [comment]
> it always looks like I've done twice the amount of work I really need to.

This is really just a mini-version of an encode-decode proof.  You have something defined inductively, and you characterize it as equivalent to something else defined recursively.  Both definitions are useful and we may want to keep them both around.  A DProp can do exactly this, keeping the underlying inductive type together with a proof of its decidability that encapsulates the recursively defined type.  So maybe the point is that we should use them this way: don't define a DProp by recursion, instead define an hProp by induction and prove by recursion that it's decidable, making it into a DProp.  I think it ought to be the case that we can still do "proofs by simplification" in concrete cases by simplifying the proof of decidability rather than the DProp itself.

This is sort of equivalent to the ssr approach where the proof of decidability "is" the boolean version.  The point of the previous discussion was that in defining a boolean predicate separately, you've divorced it from its meaning and you have to invoke complicated things like reflection in order to make the connection to the inductive property you started from.  A proof of decidability is attached intrinsically to its meaning.

**Comment by Alizter** [comment]
I'm closing this discussion as I don't think enforcing proof-by-reflection globally like it is done for SSR is something we want to do. The status quo seems to be fine. We can reopen later if we deem that we are unsatisfied.
