### ISSUE TITLE
Redefine `prod` as sigma type

### ISSUE THREAD

**Issue by Alizter** [HoTT/Coq-HoTT#1623]
I can't remember if we discussed this before. Is there any reason we want to have a separate prod? I think we could redefine it as a special case of a sigma type in a pretty useable way. This would mean we wouldn't have to have lemmas going back and forth any longer.

**Comment by JasonGross** [comment]
We'd need to make `fst` and `snd` notations if we wanted to not lose primitive projections.  We'd have to jump through a bunch of hoops if we wanted to ensure that `fst` and `snd` could only be used with `prod` without making the term bigger.  (And these hoops would probably be incompatible with passing the projections to higher order functions.).  We'd probably want `pair` to be a notation as well, so that reduction works smoothly. And it's not clear to me whether or not type inference would be good enough to make everything else work smoothly.  We could try it though

**Comment by mikeshulman** [comment]
I'm dubious that this would turn out to be a good idea.  But I suppose you could experiment.

**Comment by Alizter** [comment]
This is not particularly a useful thing to do. I haven't seen any places which would benefit from seamless conversion between products and sigma types yet.
