### ISSUE TITLE
Use `Attributes` command to deprecate usage of certain .v files

### ISSUE THREAD

**Issue by Alizter** [HoTT/Coq-HoTT#1904]
Coq 8.19 has a feature where one can write
```
Attributes deprecated(note="A deprecated").
```
in a file a.v and when b.v `Require`s `a`, then a warning it emitted. This would be useful to have in our index files such as `Basics.v`. Something like:
```
Attributes deprecated(note="Usage of index files in HoTT library is deprecated. Please use only the necessary components. This helps keep the build fast. ").
```
That way we can get warnings when we use them in the library. We can fix these warnings giving us a fast build and discouraging people from using the index files. However, importantly we do not prevent their usage and only make it discouraged. This means for quick prototyping you can still use the index files.

We could also think about adding a way to ignore this warning in external libraries, but I'm not fully certain how this can be done. Something with warning categories ought to be possible. That way, external libraries using the HoTT library won't have trouble using it.

**Comment by jdchristensen** [comment]
I think in many cases, it really is best to `Require Import Basics.`  It's only for "low-level" things like WildCat and Types, where we can gain a bit of efficiency by being specific there.  There are only a few other meta-files where I think it's somewhat important to be careful with the import, e.g. Spaces.Nat (since Spaces.Nat.Paths has a lot of dependencies) and Truncations.v (because often only one of the files in the folder is needed, and again the dependencies are slightly non-trivial).  But when you do really need all of the files in one of these cases, I think we should still allow people to import the meta-file without causing a warning.

**Comment by Alizter** [comment]
I guess this will just end up being annoying and it is really up to us to keep the build fast rather than annoying everybody about it.
